# Generated by Django 5.0.7 on 2024-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_departamento_created_departamento_creater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='creater',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='deleter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocuentabancaria',
            name='updater',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
