# Generated by Django 5.0.7 on 2024-08-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraDetalles',
            new_name='CompraDetalle',
        ),
    ]
